export const APP_NAME = 'wake.lol';
export const BASE_URL = 'https://wake.lol/';
export const FEATURES = 'width=300,height=200';
export const THEME_COUNT = 2;
export const THEME_INDEX_DATASET_KEY = 'themeIndex';
export const THEME_INDEX_STORAGE_KEY = 'theme';
export const CSS_VAR_BG = '--color-bg';
export const CSS_VAR_FG = '--color-fg';
export const CSS_VAR_ACTIVE_BG = '--color-active-bg';
export const CSS_VAR_ACTIVE_FG = '--color-active-fg';
export const CSS_VAR_INACTIVE_BG = '--color-inactive-bg';
export const CSS_VAR_INACTIVE_FG = '--color-inactive-fg';
export const ID_BELOW_THE_FOLD = 'below-the-fold';
// export const IS_FILE_PROTOCOL = window.location.protocol === 'file:';
